# Class Result Analysis Project

## Project Objective

The objective of this project is to analyze student academic performance using semester SPI data and derive meaningful insights using Python-based data analytics and visualization techniques.

---

## Data Loading

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("CLASS_RESULT_PROJECT_DATASET.xlsx")

##### Missing SPI values in certain semesters represent students with due credits/backlogs and were retained for analytical purposes instead of being removed.

In [5]:
df.head()

,S.No,STUDENT NAME,ROLL NO,Gender,SPI - 1st Sem,SPI - 2nd Sem,SPI - 3rd Sem,SPI - 4th Sem,SPI - 5th Sem,SPI - 6th Sem,Attendance,Stay
0,1,Aarti Suryvanshi,23113001,Female,5.95,7.25,6.69,7.26,7.66,7.60,85,Day Scholar
1,2,Aaryan lahre,23113002,Male,6.30,6.80,NaN,NaN,NaN,NaN,40,Day Scholar
2,3,Aaryansh Dwivedi,23113003,Male,7.70,7.50,6.60,6.50,7.23,6.56,76,Day Scholar
3,4,Aayushman Dash,23113004,Male,8.50,9.20,8.19,9.15,8.19,8.78,89,Hosteller
4,5,Abhinav Anand,23113006,Male,8.33,8.75,8.00,NaN,7.23,7.52,71,Hosteller

In [6]:
df.columns

Index(['S.No', 'STUDENT NAME', 'ROLL NO', 'Gender', 'SPI - 1st Sem',
       'SPI - 2nd Sem', 'SPI - 3rd Sem', 'SPI - 4th Sem', 'SPI - 5th Sem',
       'SPI - 6th Sem', 'Attendance', 'Stay'],
      dtype='object')

## Data Understanding

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   S.No           69 non-null     int64
 1   STUDENT NAME   69 non-null     object
 2   ROLL NO        69 non-null     int64
 3   Gender         69 non-null     object
 4   SPI - 1st Sem  68 non-null     float64
 5   SPI - 2nd Sem  69 non-null     float64
 6   SPI - 3rd Sem  66 non-null     float64
 7   SPI - 4th Sem  56 non-null     float64
 8   SPI - 5th Sem  63 non-null     float64
 9   SPI - 6th Sem  63 non-null     float64
 10  Attendance     69 non-null     int64
 11  Stay           69 non-null     object
dtypes: float64(6), int64(3), object(3)
memory usage: 6.6+ KB

In [8]:
df.describe()

,S.No,ROLL NO,SPI - 1st Sem,SPI - 2nd Sem,SPI - 3rd Sem,SPI - 4th Sem,SPI - 5th Sem,SPI - 6th Sem,Attendance
count,69.000000,6.900000e+01,68.000000,69.000000,66.000000,56.000000,63.000000,63.000000,69.000000
mean,35.000000,2.311310e+07,7.889265,8.194638,7.627879,7.839107,7.894127,8.052698,76.898551
std,20.062403,2.264420e+02,1.006723,0.862499,1.011457,0.998760,0.741371,0.763226,13.260007
min,1.000000,2.311300e+07,5.570000,6.450000,5.610000,5.880000,5.700000,6.340000,3.000000
25%,18.000000,2.311302e+07,7.160000,7.580000,6.880000,7.170000,7.470000,7.580000,74.000000
50%,35.000000,2.311304e+07,8.000000,8.200000,7.590000,8.090000,7.950000,8.080000,78.000000
75%,52.000000,2.311306e+07,8.565000,9.000000,8.272500,8.532500,8.330000,8.410000,85.000000
max,69.000000,2.311390e+07,9.580000,9.620000,9.690000,9.800000,9.660000,9.780000,95.000000

In [9]:
df.shape

(69, 12)

In [10]:
df.isnull().sum()

S.No              0
STUDENT NAME      0
ROLL NO           0
Gender            0
SPI - 1st Sem     1
SPI - 2nd Sem     0
SPI - 3rd Sem     3
SPI - 4th Sem    13
SPI - 5th Sem     6
SPI - 6th Sem     6
Attendance        0
Stay              0
dtype: int64

In [11]:
df_backup = df.copy()